name: mobx
version: 1.2.1+2
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  collection: ^1.15.0-nullsafety.3
  coverage: ^0.13.11
  fake_async: ^1.1.1
  mockito: ^4.1.2
  test: ^1.16.0-nullsafety.5
