name: mobx
version: 0.3.3+1
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."
authors:
  - Pavan Podila <pavan@pixelingene.com>
  - Joni Katajamäki <joni.katajamaki@gmail.com>
  - Remi Rousselet <darky12s@gmail.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.6.3
  fake_async: ^1.0.1
  mockito: ^4.0.0
  test_coverage: ^0.2.3
