name: mobx
version: 2.0.0-nullsafety.1
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety

dev_dependencies:
  collection: ^1.15.0-nullsafety
  coverage: ^0.14.2
  fake_async: ^1.2.0-nullsafety
  mockito: ^4.1.2
  test: ^1.16.0-nullsafety
