coverage:
  range: 90..100
  status:
    project:
      default: off
      mobx:
        flags: mobx
      mobx_codegen:
        flags: mobx_codegen
      flutter_mobx:
        flags: flutter_mobx

flags:
  # filter the folder(s) you wish to measure by that flag
  mobx:
    # only include files in the mobx folder
    paths:
      - mobx/lib/
  mobx_codegen:
    paths:
      - mobx_codegen/lib/
  flutter_mobx:
    paths:
      - flutter_mobx/lib/
