name: mobx
version: 0.0.1
description: Reactive State Management for Dart apps.
author: Pavan Podila <pavan@pixelingene.com>
homepage: https://mobx.js.org

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.5.1