name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 1.1.2

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  build_resolvers: ^1.5.4
  meta: ^1.1.0
  mobx: ^2.0.0-null-safety.2
  path: ^1.6.2
  source_gen: ^0.9.10

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  coverage: ^1.0.1
  logging: ^1.0.0
  mockito: ^5.0.0
  test: ^1.9.4
