name: flutter_mobx
description:
  Flutter integration for MobX. It provides a set of Observer widgets that automatically rebuild
  when the tracked observables change.
version: 0.3.4
authors:
  - Joni Katajamäki <joni.katajamaki@gmail.com>
  - Pavan Podila <pavan@pixelingene.com>
  - Scott Hyndman <scotty.hyndman@gmail.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  mobx: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
